services:
  plex-media-server:
    image: plexinc/pms-docker
    container_name: plex-media-server
    hostname: plex-media-server
    environment:
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN} #Log on your plex account and generate one in plex.tv/claim
    volumes:
      - ${PLEX_CONFIG_FOLDER:-./config}:/config
      - ${PLEX_TRANSCODE_FOLDER:-./transcodes}:/transcodes
      - ${PLEX_DOWNLOADS_FOLDER:-./downloads}:/downloads
      - ${TVSHOWS_FOLDER}:/tvshows:ro
      - ${MOVIES_FOLDER}:/movies:ro
      - ${ANIMES_FOLDER}:/animes:ro
    devices:  #needed if you want hardware transcode
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      local:
      external:
        ipv4_address: ${PLEX_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}