services:
  plex-media-server:
    image: plexinc/pms-docker
    container_name: plex-media-server
    hostname: plex-media-server
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN} #Log on your plex account and generate one in plex.tv/claim
    volumes:
      - ${CONFIG_FOLDER:-./config}:/config
      - ${TRANSCODE_FOLDER:-./transcodes}:/transcodes
      - ${DOWNLOADS_FOLDER:-./downloads}:/downloads
      - ${TVSHOWS_FOLDER}:/tvshows:ro
      - ${MOVIES_FOLDER}:/movies:ro
      - ${ANIMES_FOLDER}:/animes:ro
    devices:  #needed if you want hardware transcode
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${PLEX_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}