services:
  plex-media-server:
    image: plexinc/pms-docker
    container_name: plex-media-server
    hostname: plex-media-server
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN} #Log on your plex account and generate one in plex.tv/claim
    volumes:
      - ${PLEX_CONFIG_FOLDER:-./config}:/config
      - ${PLEX_TRANSCODE_FOLDER:-./transcodes}:/transcodes
      - ${PLEX_DOWNLOADS_FOLDER:-./downloads}:/downloads
      - ${TVSHOWS_FOLDER}:/tvshows:ro
      - ${MOVIES_FOLDER}:/movies:ro
      - ${ANIMES_FOLDER}:/animes:ro
    devices:  #needed if you want hardware transcode
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      local:
      external:
        ipv4_address: ${PLEX_IP}

  scheduler:
    image: mcuadros/ofelia:0.3
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-exec.plextraktsync.schedule: "@every 2h"
      ofelia.job-exec.plextraktsync.container: "plextraktsync"
    networks:
      local:

  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: sync
    container_name: plextraktsync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PLEX_IP=plex-media-server
      - PLEX_TOKEN=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${PLEXTRAKTSYNC_CONFIG_FOLDER:-./config}:/app/config
      - ./plex-trakt-sync/servers.yml:/app/config/servers.yml:ro
    restart: unless-stopped
    networks:
      local:

networks:
  local:
    name: plex-local-network
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}